"""sync_existing_db_columns

Revision ID: 7c8aff89d580
Revises: 0001
Create Date: 2026-06-08 12:04:54.161598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c8aff89d580'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bin_scans', sa.Column('smart_bin_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bin_scans_smart_bin_id'), 'bin_scans', ['smart_bin_id'], unique=False)
    op.create_foreign_key(None, 'bin_scans', 'smart_bins', ['smart_bin_id'], ['id'])
    op.alter_column('posts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'moderation_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('posts', 'moderated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'moderated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('posts', 'moderation_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('posts', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'bin_scans', type_='foreignkey')
    op.drop_index(op.f('ix_bin_scans_smart_bin_id'), table_name='bin_scans')
    op.drop_column('bin_scans', 'smart_bin_id')
    # ### end Alembic commands ###
